### ISSUE TITLE
Disable update checker

### ISSUE THREAD

**Issue by grawlinson** [abdfnx/doko#19]
It would be much better if the update checker was *opt-in*, or disabled entirely. As it is, it creates a network call every time `doko` is invoked. Not ideal when travelling or in airport mode.

**Comment by abdfnx** [comment]
Hi @grawlinson, you can disable the update checker by executing `doko settings set show_update false` command

**Comment by abdfnx** [comment]
is everything okay @grawlinson

**Comment by grawlinson** [comment]
Yes, thank you for asking. :)
